apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodecamp-app
  labels:
    app: kodecamp-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: kodecamp-app
  template:
    metadata:
      labels:
        app: kodecamp-app
    spec:
      containers:
      - name: kodecamp-app
        image: kodecamp-web:latest
        imagePullPolicy: Never
        env:
          - name: MESSAGE
            valueFrom: 
             configMapKeyRef:
               name: hello-config
               key: message
          - name: PASSWORD
            valueFrom: 
              secretKeyRef:
                name: my-secret
                key: password
        ports:
        - containerPort: 8080
